demo_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from demo_app.views import upload, capture_images, reset_captured_images

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', upload, name='upload'),
    path('capture_images/', capture_images, name='capture_images'),
    path('reset_captured_images/', reset_captured_images, name='reset_captured_images'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

demo_app/models.py
from django.db import models
import os


def get_upload_path(instace, filename):
    return os.path.join("{}".format(instace.demo_id.name), filename)


class DemoObject(models.Model):
    """
    A modal to store the demo objects.
    """
    class Meta:
        verbose_name_plural = "Demo Objects"

    name = models.CharField(max_length=266)

    def __str__(self):
        return self.name
    


class DemoFile(models.Model):
    """
    A modal to files related to DemoApp.
    """
    class Meta:
        verbose_name_plural = "Demo Files"

    demo_id = models.ForeignKey(DemoObject, verbose_name="Demo Object", on_delete=models.CASCADE)
    demo_file = models.FileField(upload_to=get_upload_path)

    def __str__(self):
        return os.path.basename(self.demo_file.name)
    


class DemoWebcamImage(models.Model):
    """
    A modal to store the images uploaded from webcam.
    """
    class Meta:
        verbose_name_plural = "Demo Webcam Images"

    demo_id = models.ForeignKey(DemoObject, verbose_name="Demo Object", on_delete=models.CASCADE)
    demo_image = models.ImageField(upload_to=get_upload_path)

    def __str__(self):
        return os.path.basename(self.demo_image.name)
    

demo_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.core.files import File
from demo_project.settings import BASE_DIR
from .models import DemoObject, DemoFile, DemoWebcamImage
import cv2, json, os, base64
from django.core.files.base import ContentFile
from django.core.files.storage import FileSystemStorage


DATA_PATH = os.path.join(BASE_DIR, 'data/')
CAP_PATH = os.path.join(BASE_DIR, 'captured/')


def clean_dir(path):
    """
    A function to clean the specified directory.
    """
    success = True
    message = ""

    try:
        dir = path
        for f in os.listdir(dir):
            os.remove(os.path.join(dir, f))

    except Exception as e:
        success = False
        message = e

    datas = {
        "success": success,
        "message": message
    }
    return datas

def upload(request):
    """
    A function to upload the files and images to entered name.
    """
    if request.method == 'POST': 
        try:
            name = request.POST['name']
            image_data = request.POST.get('webcam_images')
            image_list = image_data.split('data:image/png')
            webcam_images = []

            folder_path = os.path.join(DATA_PATH, name)

            if not os.path.exists(folder_path):
                os.makedirs(folder_path)

            for item in image_list:
                if item == 'data:image/png' or item == '':
                    continue
                else:
                    webcam_images.append(item)
            

            for index, webcam_image in enumerate(webcam_images):
                imgstr = webcam_image.split('base64,')[1]
                data = ContentFile(base64.b64decode(imgstr))
                myfile = "{}.png".format(index+1)
                fs = FileSystemStorage(location=folder_path)
                filename = fs.save(myfile, data)

            for item in request.FILES.getlist('files'):
                file_name = os.path.join(folder_path, item.name)
                with open(file_name, '+wb') as f:
                    for chunk in item.chunks():
                        f.write(chunk)

            messages.success(request, 'Data added to folder {}'.format(name))
            
        except Exception as e:
            messages.error(request, e)

        clean_dir(CAP_PATH) #remove the duplicate data
        return redirect('upload')
    else:
        return render(request, 'demo_app/upload_form.html')


def capture_images(request):
    """
    A function to activate and capture images using webcam.
    """
    if not os.path.exists(CAP_PATH):
        os.makedirs(CAP_PATH)

    try:
        cam = cv2.VideoCapture(0)
        cv2.namedWindow("Capture")

        img_counter = 1
        img_list = []

        while True:
            ret, frame = cam.read()

            if not ret:
                break

            cv2.imshow("Capture", frame)
            k = cv2.waitKey(1)

            if k%256 == 27 or cv2.getWindowProperty("Capture", cv2.WND_PROP_VISIBLE) < 1:
                # ESC or X pressed
                break

            elif k%256 == 32:
                # SPACE pressed
                img_name = "image_{}.png".format(img_counter)
                cv2.imwrite(CAP_PATH + img_name, frame)
                
                img_list.append(img_name)
                img_counter += 1

        cam.release()
        cv2.destroyAllWindows()

        datas = {
            "success": True,
            "img_list": img_list,
            "count": len(img_list)
        }

    except Exception as e:
        datas ={
            "success": False,
            "message": e
        }

    return HttpResponse(json.dumps(datas), content_type='application/json')

def reset_captured_images(request):
    """
    A futnction to reset the captured images.
    """
    datas = clean_dir(CAP_PATH)
    return HttpResponse(json.dumps(datas), content_type='application/json')

templates/demo_app/upload_form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Project</title>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container" style="margin-top: 40px;">
        <center><h3>Upload Form</h3></center>
        <div class="row justify-content-center" style="margin-top: 40px;">
                <form action='.' method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %} alert-dismissable form-control" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}
                    <div class="form-group">
                        <label for="id_name">Name</label>
                        <input type="text" class="form-control" id="id_name" name="name" required>
                        <small class="form-text text-muted">This name will be used as the folder name while uploading the files.</small>
                    </div>
                    <div class="form-group">
                        <label for="id_files">Files</label>
                        <input type="file" class="form-control" id="id_files" name="files" multiple>
                    </div>
                    <div class="form-group">
                        <label for="btn_capture">Webcam</label>
                        <div class="contentarea">
                            <div class="camera">
                                <video id="video" style="display: none;">Video stream not available.</video>
                            </div>
                            <button id="btn_webcam_open" type="button" class="btn btn-secondary form-control">Open Webcam</button>
                            <div class="video_action text-center">
                                <button id="btn_webcam_capture" type="button" class="btn btn-success" style="display: none;">Capure Image</button>
                                <button id="btn_webcam_close" type="button" class="btn btn-danger" style="display: none;">Close Webcam</button>
                            </div>
                            <small id="images_count" class="form-text text-muted"></small>
                            <canvas id="canvas" style="display: none;"></canvas>
                            <div class="output" style="display: none;">
                                <img id="photo" style="display: none;">
                            </div>
                        </div>
                    </div>
                    <div class="form-group" style="display: none;">
                        <input type="hidden" class="form-control" id="id_webcam_images" name="webcam_images">
                    </div>
                    <div class="form-group">
                        <button type="reset" class="btn btn-danger" id="btn_reset" data-toggle="tooltip" title="Clear Form">RESET</button>
                        <button type="submit" class="btn btn-primary" id="btn_sumbit" data-toggle="tooltip" title="Upload to folder">UPLOAD FILES</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
<script src="{% static 'webcam.js' %}"></script>
</html>